stages:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_SERVER: POSTGRES_SERVER
      POSTGRES_PORT: POSTGRES_PORT
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_DSN: POSTGRES_DSN
    ports:
      - "5432:5432"

  web:
    image: python:3.11
